---
title: Workflow

type: object

x-box-resource-id: workflow
x-box-tag: workflows
x-box-variant: standard

description: |-
  A standard representation of a workflow.

properties:
  id:
    type: string
    description: The unique identifier for the workflow
    example: "11446498"
