---
title: Workflow

type: object

x-box-resource-id: workflow
x-box-variant: standard

description: |-
  Box Relay Workflows are objects that represent a named collection of flows.

allOf:
  - $ref: '#/components/schemas/Workflow--Mini'
  - properties:
      flows:
        type: array
        description: |-
          A list of flows assigned to a workflow.
        items:
          type: object
          description: |-
            A step in a Box Relay Workflow. Each flow contains a `Trigger` and
            a collection of Outcomes to perform once the conditions of a
            `Trigger` are met.
          properties:
            id:
              type: string
              description: The identifier of the flow
              example: '12345'
            type:
              type: string
              description: The type of the flow
              example: flow
              enum:
                - flow
