# The name of this GH action
name: Netlify

# Defines when this action should be run
on:
  # Run on any Push
  push:
    branches:
      - en
      - en-staging
      - jp

jobs:
  build-en:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/en'
    timeout-minutes: 3

    steps:
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: boxdev
          NETLIFY_DEPLOY_MESSAGE: OpenAPI Update
          NETLIFY_DEPLOY_TO_PROD: true

  build-en-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/en-staging'
    timeout-minutes: 3

    steps:
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: boxdev-staging
          NETLIFY_DEPLOY_MESSAGE: OpenAPI Update
          NETLIFY_DEPLOY_TO_PROD: true

  build-jp:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/jp'
    timeout-minutes: 3

    steps:
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: boxdevjp
          NETLIFY_DEPLOY_MESSAGE: OpenAPI Update
          NETLIFY_DEPLOY_TO_PROD: true